build.gradle, src/main/java/org/example/auctify/config/CorsMvcConfig.java, src/main/java/org/example/auctify/config/CustomFailureHandler.java, src/main/java/org/example/auctify/config/SecurityConfig.java, src/main/java/org/example/auctify/controller/HelloTestController.java, src/main/java/org/example/auctify/controller/oauth2/MainController.java, src/main/java/org/example/auctify/controller/oauth2/MyController.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/social/CustomOauth2User.java, src/main/java/org/example/auctify/dto/social/GoogleResponse.java, src/main/java/org/example/auctify/dto/social/KakaoResponse.java, src/main/java/org/example/auctify/dto/social/OAuth2Response.java, src/main/java/org/example/auctify/dto/social/UserDTO.java, src/main/java/org/example/auctify/dto/user/RequestUserDTO.java, src/main/java/org/example/auctify/dto/user/Role.java, src/main/java/org/example/auctify/entity/user/UserEntity.java, src/main/java/org/example/auctify/jwt/JWTFilter.java, src/main/java/org/example/auctify/jwt/JWTUtil.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java, src/main/java/org/example/auctify/repository/user/UserRepository.java, src/main/java/org/example/auctify/service/user/CustomOAuth2UserService.java
Security 개발 및 OAuth2.0연동 
구글, 카카오 소셜 로그인 구현 
로그인 요청 경로 
URI/oauth2/authorization/kakao
URI/oauth2/authorization/google
URI/ <-  모두 허용
URI/my  <- 로그인 회원만 허용
close #8
=> [Feature]Security 개발 및 OAuth2.0연동

src/test/java/org/example/auctify/AuctifyApplicationTests.java, src/test/resources/application.yml
jwt properties에러 수정 
clsoe #10
=> [Bug] jwt-propertieserrorfix

src/main/java/org/example/auctify/jwt/JWTUtil.java
=> [Bug] fix expired 만료시간 에러 수정

.gitignore, build.gradle, src/main/java/org/example/auctify/config/S3Config.java, src/main/java/org/example/auctify/config/SecurityConfig.java, src/main/java/org/example/auctify/controller/presigned/PresignedController.java, src/main/java/org/example/auctify/dto/s3/ImageRequestDTO.java, src/main/java/org/example/auctify/dto/s3/PresignedUrlResponseDTO.java, src/main/java/org/example/auctify/jwt/JWTFilter.java, src/main/java/org/example/auctify/service/s3/FileUploadService.java, src/main/resources/application-local.yml
PresignedURL 발급 컨트럴러 구현
close #14
=> [Feature]PresignedURL 구현

src/main/java/org/example/auctify/config/CorsMvcConfig.java, src/main/java/org/example/auctify/config/SecurityConfig.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
=> [Fix] cors에러수정

src/main/java/org/example/auctify/config/CorsMvcConfig.java, src/main/java/org/example/auctify/config/SecurityConfig.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
=> [Fix]토큰,cors에러수정

src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/user/ProfileDTO.java
UserController Swagger명세서 부분 구현 
close #22
=> [Feat] UserControllerSwagger구현

src/main/java/org/example/auctify/config/security/CustomUserDetails.java, src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/config/security/s3/S3Config.java, src/main/java/org/example/auctify/controller/oauth2/MyController.java, src/main/java/org/example/auctify/dto/social/GoogleResponse.java, src/main/java/org/example/auctify/dto/social/KakaoResponse.java, src/main/java/org/example/auctify/entity/user/UserEntity.java, src/main/java/org/example/auctify/service/user/CustomOAuth2UserService.java, src/main/java/org/example/auctify/service/user/CustomUserDetailsService.java
UserDetails구현 인증정보 가져오기 
close #23
=> [Feat]UserDetails인증정보가져오기

src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/Goods/AuctionGoodsDTO.java, src/main/java/org/example/auctify/dto/Goods/FeedbackDTO.java, src/main/java/org/example/auctify/dto/Goods/GoodsStatus.java, src/main/java/org/example/auctify/dto/social/UserDTO.java, src/main/java/org/example/auctify/dto/user/AddressDTO.java, src/main/java/org/example/auctify/dto/user/MannerTemperatureDTO.java, src/main/java/org/example/auctify/dto/user/ProfileDTO.java, src/main/java/org/example/auctify/dto/user/RequestUserDTO.java, src/main/java/org/example/auctify/dto/user/UserInfoDTO.java, src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
=> [Feat]user swagger 반환 dto 작성

src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/Goods/AuctionGoodsDTO.java, src/main/java/org/example/auctify/dto/Goods/FeedbackDTO.java, src/main/java/org/example/auctify/dto/user/MannerTemperatureDTO.java, src/main/java/org/example/auctify/dto/user/UserInfoRequestDTO.java, src/main/java/org/example/auctify/dto/user/UserInfoResponseDTO.java
=> [Modify] UserSwagger 수정

src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/auction/Goodscontroller.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/Goods/AuctionResponseGoodsDTO.java, src/main/java/org/example/auctify/dto/Goods/BidPurchaseRequestDTO.java, src/main/java/org/example/auctify/dto/Goods/BidPurchaseResponseDTO.java, src/main/java/org/example/auctify/dto/Goods/BidRequestDTO.java, src/main/java/org/example/auctify/dto/Goods/BidResponseDTO.java, src/main/java/org/example/auctify/dto/Goods/GoodsRequestDTO.java, src/main/java/org/example/auctify/dto/Goods/LikeRequestDTO.java, src/main/java/org/example/auctify/dto/Goods/LikeResponseDTO.java, src/main/java/org/example/auctify/dto/Goods/ReviewRequestDTO.java, src/main/java/org/example/auctify/dto/Goods/ReviewResponseDTO.java, src/main/java/org/example/auctify/dto/Goods/SearchDTO.java
auction 관련 swagger 구현 
clseo #26
=> [Feat]auctionSwagger구현

src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
=> [Feat] 스웨거 get요청시 파라미터로 수정

src/main/java/org/example/auctify/entity/bidHistory/BidHistoryEntity.java, src/main/java/org/example/auctify/entity/like/LikeEntity.java, src/main/java/org/example/auctify/entity/payment/PaymentEntity.java, src/main/java/org/example/auctify/entity/review/ReviewEntity.java
Auctify 프로젝트 엔티티작성 
https://www.erdcloud.com/d/WKLaQoYKsKanAM9Hq 참고 
close #35
=> [Feature] entity create

src/main/java/org/example/auctify/config/security/CustomUserDetails.java, src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/auction/Goodscontroller.java, src/main/java/org/example/auctify/controller/oauth2/MyController.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/social/CustomOauth2User.java, src/main/java/org/example/auctify/dto/social/UserDTO.java, src/main/java/org/example/auctify/dto/user/UserInfoResponseDTO.java, src/main/java/org/example/auctify/entity/user/UserEntity.java, src/main/java/org/example/auctify/jwt/JWTFilter.java, src/main/java/org/example/auctify/jwt/JWTUtil.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java, src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java, src/main/java/org/example/auctify/repository/goods/GoodsCategoryRepository.java, src/main/java/org/example/auctify/repository/goods/GoodsImageRepository.java, src/main/java/org/example/auctify/repository/goods/GoodsRepository.java, src/main/java/org/example/auctify/repository/like/LikeRepository.java, src/main/java/org/example/auctify/repository/payment/PaymentRepository.java, src/main/java/org/example/auctify/repository/review/ReviewRepository.java, src/main/java/org/example/auctify/repository/user/AddressRepository.java, src/main/java/org/example/auctify/repository/user/UserRepository.java, src/main/java/org/example/auctify/service/user/CustomOAuth2UserService.java, src/main/java/org/example/auctify/service/user/UserService.java
=> [Feat]Profile조회API구현

src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/auction/Goodscontroller.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/Goods/GoodsResponseSummaryDTO.java, src/main/java/org/example/auctify/dto/Goods/ReviewDetailResponseDTO.java, src/main/java/org/example/auctify/dto/bid/BidHistoryResponseDTO.java, src/main/java/org/example/auctify/dto/like/LikeGoodsResponseDTO.java, src/main/java/org/example/auctify/dto/response/ApiResponseDTO.java, src/main/java/org/example/auctify/dto/user/AddressDTO.java, src/main/java/org/example/auctify/dto/user/AddressRequestDTO.java, src/main/java/org/example/auctify/dto/user/UserChangedProfileResponseDTO.java, src/main/java/org/example/auctify/dto/user/UserInfoRequestDTO.java, src/main/java/org/example/auctify/entity/Goods/GoodsCategoryEntity.java, src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java, src/main/java/org/example/auctify/entity/Goods/GoodsImageEntity.java, src/main/java/org/example/auctify/entity/bidHistory/BidHistoryEntity.java, src/main/java/org/example/auctify/entity/like/LikeEntity.java, src/main/java/org/example/auctify/entity/payment/PaymentEntity.java, src/main/java/org/example/auctify/entity/review/ReviewEntity.java, src/main/java/org/example/auctify/entity/user/AddressEntity.java, src/main/java/org/example/auctify/entity/user/UserEntity.java, src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java, src/main/java/org/example/auctify/repository/goods/GoodsRepository.java, src/main/java/org/example/auctify/repository/like/LikeRepository.java, src/main/java/org/example/auctify/repository/review/ReviewRepository.java, src/main/java/org/example/auctify/repository/user/AddressRepository.java, src/main/java/org/example/auctify/repository/user/UserRepository.java, src/main/java/org/example/auctify/service/user/UserService.java
UserController 세부사항 구현 
close #41
=> [Feature]UserController구현

src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/auction/Goodscontroller.java
ApiResponseDTO 일괄적용 
close #43
=> [Chore]ApiResponseDTO적용

src/main/java/org/example/auctify/controller/auction/Goodscontroller.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/dto/duplication/DuplicationDTO.java, src/main/java/org/example/auctify/dto/user/UserChangedProfileResponseDTO.java, src/main/java/org/example/auctify/dto/user/UserInfoRequestDTO.java, src/main/java/org/example/auctify/repository/user/UserRepository.java, src/main/java/org/example/auctify/service/user/UserService.java
=> [Freature]DuplicationCheck기능추가

src/main/java/org/example/auctify/config/security/CustomUserDetails.java, src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/dto/social/CustomOauth2User.java, src/main/java/org/example/auctify/jwt/JWTFilter.java
=> [Fix]소셜로그인후권한에러수정

src/main/java/org/example/auctify/dto/like/LikeGoodsResponseDTO.java, src/main/java/org/example/auctify/service/user/UserService.java
=> [Chore]찜목록전달데이터수정

build.gradle, src/main/java/org/example/auctify/config/CorsMvcConfig.java, src/main/java/org/example/auctify/config/querydsl/QueryDslConfig.java, src/main/java/org/example/auctify/config/security/CustomUserDetails.java, src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/controller/tossPayments/PaymentController.java, src/main/java/org/example/auctify/dto/tossPayments/PayRequestDTO.java, src/main/java/org/example/auctify/dto/tossPayments/PaymentResponseDTO.java, src/main/java/org/example/auctify/dto/tossPayments/TossPaymentsResponseDTO.java, src/main/java/org/example/auctify/entity/payment/PaymentEntity.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java, src/main/java/org/example/auctify/service/payment/PaymentService.java
=> [Feature]결제API구현

src/main/java/org/example/auctify/controller/tossPayments/PaymentController.java, src/main/java/org/example/auctify/controller/tossPayments/PaymentInterface.java, src/main/java/org/example/auctify/dto/tossPayments/PayRequestDTO.java
=> [Chore]결제Swagger수정

src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/service/auction/GoodsService.java
URL 권한설정에서 모드 접근 가능한 URL의 경우 permitAll설정 
close #59
=> [Chore]URL권한설정수정

src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/controller/auction/GoodsController.java, src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/dto/bid/BidSummaryDTO.java, src/main/java/org/example/auctify/repository/goods/GoodsRepository.java, src/main/java/org/example/auctify/service/auction/GoodsService.java
=> [Feature]요약입찰내역API구현

src/main/java/org/example/auctify/scheduler/AuctifyScheduledTask.java
=> [Freature]스케줄러기능구현

src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java, src/main/java/org/example/auctify/service/auction/GoodsService.java
=> [Feature]입찰시경매상태체크

src/main/java/org/example/auctify/controller/oauth2/MyController.java, src/main/java/org/example/auctify/dto/response/ApiResponseDTO.java, src/main/resources/application.yml
=> [Feat]로그인유저정보전달

src/main/java/org/example/auctify/config/CorsMvcConfig.java, src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/entity/user/UserEntity.java, src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java, src/main/java/org/example/auctify/repository/user/UserRepository.java, src/main/java/org/example/auctify/service/user/UserService.java
=> [Fix]마이프로필수정API

src/main/java/org/example/auctify/oauth2/CustomSuccessHandler.java
=> [Chore]로그인성공로직수정

src/main/java/org/example/auctify/config/chat/WebSocketConfig.java, src/main/java/org/example/auctify/controller/auction/GoodsController.java, src/main/java/org/example/auctify/controller/chat/ChatMessageController.java, src/main/java/org/example/auctify/controller/notification/NotificationController.java, src/main/java/org/example/auctify/dto/chat/JoinRoomDto.java, src/main/java/org/example/auctify/dto/chat/LeaveRoomDto.java, src/main/java/org/example/auctify/dto/chat/MessageDto.java, src/main/java/org/example/auctify/dto/notification/ChatNotificationDto.java, src/main/java/org/example/auctify/dto/notification/NotificationType.java, src/main/java/org/example/auctify/entity/notification/NotificationEntity.java, src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java, src/main/java/org/example/auctify/repository/goods/GoodsRepository.java, src/main/java/org/example/auctify/repository/notification/NotificationRepository.java, src/main/java/org/example/auctify/scheduler/AuctifyScheduledTask.java, src/main/java/org/example/auctify/service/auction/GoodsService.java, src/main/java/org/example/auctify/service/chat/ChatMessageService.java, src/main/java/org/example/auctify/service/chat/UserSessionService.java, src/main/java/org/example/auctify/service/notification/NotificationSender.java, src/main/java/org/example/auctify/service/notification/NotificationService.java, src/main/java/org/example/auctify/util/websocket/StompHandler.java
=> [Feature] 알림 API 구현

.github/workflows/deploy.yml, src/main/java/org/example/auctify/entity/Goods/GoodsEntity.java, src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepository.java, src/main/java/org/example/auctify/repository/goods/GoodsRepository.java, src/main/java/org/example/auctify/service/auction/GoodsService.java
=> [Fix]유저컨트럴조회로직수정

src/main/java/org/example/auctify/controller/auction/GoodsController.java, src/main/java/org/example/auctify/repository/goods/GoodsRepositoryCustomImpl.java
=> [Fix]경매컨트럴러조회로직수정

src/main/java/org/example/auctify/controller/auction/GoodsController.java, src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/repository/goods/GoodsRepository.java, src/main/java/org/example/auctify/service/auction/GoodsService.java
=> [Fix]경매C,U,D관련API수정

src/main/java/org/example/auctify/config/CorsMvcConfig.java, src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/controller/presigned/PresignedController.java, src/main/java/org/example/auctify/controller/presigned/PresignedControllerDocs.java, src/main/java/org/example/auctify/dto/s3/DeleteImageRequestDTO.java, src/main/java/org/example/auctify/service/s3/FileUploadService.java
=> [Feature]PresignedURLDELETE구현CORS설정

src/main/java/org/example/auctify/controller/chat/ChatRoomController.java, src/main/java/org/example/auctify/controller/chat/ChatRoomControllerDocs.java, src/main/java/org/example/auctify/controller/notification/NotificationController.java, src/main/java/org/example/auctify/controller/notification/NotificationControllerDocs.java, src/main/java/org/example/auctify/service/notification/NotificationService.java
새로 구현한 API에 대해 swagger 문서 작성을 했습니다.
=> [DOCS] 스웨거 문서 작성

src/main/java/org/example/auctify/controller/sse/SSEController.java, src/main/java/org/example/auctify/controller/sse/SSEControllerDocs.java, src/main/java/org/example/auctify/service/sse/SSEService.java
Notification 구독 API에서 SSE 구독 API로 변경했습니다.
=> [Refactor] SSE 구독 API 변경

src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java
=> [Chore]SSE관련 임시 Swagger문서 수정

src/main/java/org/example/auctify/controller/auction/GoodsController.java, src/main/java/org/example/auctify/controller/auction/GoodsControllerDocs.java, src/main/java/org/example/auctify/controller/user/UserController.java, src/main/java/org/example/auctify/controller/user/UserControllerDocs.java, src/main/java/org/example/auctify/repository/bidHistory/BidHistoryRepositoryImpl.java
=> [Feat]myBidAPI재구현

src/main/java/org/example/auctify/config/security/SecurityConfig.java, src/main/java/org/example/auctify/controller/sse/SSEController.java, src/main/java/org/example/auctify/controller/sse/SSEControllerDocs.java, src/main/java/org/example/auctify/service/notification/NotificationService.java, src/main/java/org/example/auctify/service/sse/SSEService.java
- 알림 sse 구독 api
- 입찰 sse 구독 api
=> [fix] sse 구독 api 분리

build.gradle, src/main/java/org/example/auctify/config/chat/WebSocketConfig.java, src/main/java/org/example/auctify/controller/chat/ChatMessageController.java, src/main/java/org/example/auctify/controller/chat/ChatRoomController.java, src/main/java/org/example/auctify/controller/chat/ChatRoomControllerDocs.java, src/main/java/org/example/auctify/dto/chat/AuctionDto.java, src/main/java/org/example/auctify/dto/chat/EnterMessageDto.java, src/main/java/org/example/auctify/dto/chat/GetMessageHistoryResDto.java, src/main/java/org/example/auctify/dto/chat/GetOneToOneChatRoomListResDto.java, src/main/java/org/example/auctify/dto/chat/LastMessageDto.java, src/main/java/org/example/auctify/dto/chat/MessageDto.java, src/main/java/org/example/auctify/dto/chat/UserDto.java, src/main/java/org/example/auctify/entity/chat/ChatMessageEntity.java, src/main/java/org/example/auctify/entity/chat/RedisChatRoomEntity.java, src/main/java/org/example/auctify/repository/chat/ChatMessageRepository.java, src/main/java/org/example/auctify/repository/chat/ConnectedChatUserRepository.java, src/main/java/org/example/auctify/repository/chat/CustomChatMessageRepository.java, src/main/java/org/example/auctify/repository/chat/CustomChatMessageRepositoryImpl.java, src/main/java/org/example/auctify/repository/chat/UserChatRoomRepository.java, src/main/java/org/example/auctify/service/chat/ChatMessageService.java, src/main/java/org/example/auctify/service/chat/ChatRoomService.java, src/main/java/org/example/auctify/service/chat/SendEnterMessage.java, src/main/java/org/example/auctify/util/websocket/StompHandler.java
- 채팅 목록 조회 응답 수정
- 채팅 메시지 조회 응답 수정
=> [fix] 채팅 응답 형식 수정

src/main/java/org/example/auctify/dto/notification/NotificationListResDto.java, src/main/java/org/example/auctify/entity/notification/NotificationEntity.java, src/main/java/org/example/auctify/service/notification/NotificationService.java
=> [fix] 알림 응답 수정
